spring.application.name=checkpoint-project
# Configurações do Servidor
server.port=8080 # A porta padrão que usaremos.

# Configurações do Banco de Dados PostgreSQL (o nome "postgres-db" deve ser o mesmo do service no docker-compose)
spring.datasource.url=jdbc:postgresql://postgres-db:5432/mydatabase
spring.datasource.username=user
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true