name: Continuous Integration - Build & Test (Ajustado)

# Disparar esta Action a partir do evento push nas branchs: develop, feature, hotfix
on:
  push:
    branches:
      - develop
      - feature
      - hotfix

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Código
        uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      # Tarefa 1 & 2: Execução de testes (ignorada) e Empacotamento (JAR)
      # Usamos 'mvn clean package' com -DskipTests para pular a fase de 'test' do Maven.
      # Isso garante que o JAR seja criado para o CD.
      - name: Empacotar Aplicação (Gerar JAR e pular testes)
        run: mvn -B clean package -DskipTests